name: Deployment

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          yarn install

      - name: create production build
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MESSENGER_WEB_325C4 }}"
          projectId: messenger-web-325c4
          channelId: live