name: Deployment

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install

      - name: create production build
        run: yarn build

      - name: deploy to firebase
        run: yarn deploy